name: clang

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - 'documents/**'
      - '.github/workflows/analyze.yml'
      - '*.md'

jobs:
  ci_job:
    uses: ./.github/workflows/common.yml
    with:
      compiler: clang-20
      deps: clang-20 libomp-20-dev
      os: ubuntu-24.04