name: clang

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - 'documents/**'
      - '*.md'

jobs:
  21:
    uses: ./.github/workflows/common.yml
    with:
      compiler: clang-21
      deps: clang-21 libomp-21-dev