name: clang

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - 'documents/**'
      - '.github/workflows/analyze.yml'
      - '*.md'

jobs:
  ci_job:
    uses: ./.github/workflows/common.yml
    with:
      compiler: clang-21
      deps: clang-21 libomp-21-dev
      os: ubuntu-26.04