name: Build & Test

on:
  workflow_call:
    inputs:
      compiler:
        required: true
        type: string
      deps:
        required: true
        type: string
      os:
        required: true
        type: string
    outputs:
      build_output:
        value: ${{ jobs.build.outputs.result }}

jobs:
  build:
    runs-on: ${{ inputs.os }}
    outputs:
      result: ${{ steps.build_app.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (APT)
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ inputs.deps }} make

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          version: 2.21.0

      - name: Setup Conan & Configure project
        run: make setup COMPILER=${{ inputs.compiler }}

      - name: Build project
        run: make build COMPILER=${{ inputs.compiler }}

      - name: Run unit tests
        working-directory: ./build
        run: |
          ctest --output-on-failure
