name: gcc

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - 'documents/**'
      - '*.md'

jobs:
  ci_job:
    uses: ./.github/workflows/common.yml
    with:
      compiler: gcc-14
      deps: gcc-14 g++-14
      os: ubuntu-24.04