name: gcc

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - 'documents/**'
      - '*.md'

jobs:
  13:
    uses: ./.github/workflows/common.yml
    with:
      compiler: gcc-13
      deps: gcc-13 g++-13