name: gcc

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - 'documents/**'
      - '*.md'

jobs:
  15:
    uses: ./.github/workflows/common.yml
    with:
      compiler: gcc-15
      deps: gcc-15 g++-15