name: gcc

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - 'documents/**'
      - '.github/workflows/analyze.yml'
      - '*.md'

jobs:
  ci_job:
    uses: ./.github/workflows/common.yml
    with:
      compiler: gcc-15
      deps: gcc-15 g++-15
      os: ubuntu-26.04